version: '3.9'

services:
  nginx:
    container_name: quiz-nginx
    image: nginx:1.25.2-alpine
    ports:
      - "80:80"
    volumes:
      - ../nginx/conf.dev:/etc/nginx/conf.d
      - ../back_static:/opt/services/back_static
      - ../back_media:/opt/services/back_media
    networks:
      - nginx_network